### ISSUE TITLE
How to display animated stickers in android?

### ISSUE THREAD

**Issue by deepakbharanikana** [imojiengineering/imoji-android-sdk#11]
Tried using getStandardThumbnailUri(true) but not working, nothing is loading.. can we have this in messaging sample?

**Comment by nkhoshini** [comment]
We'll be adding support for animated content in the [Imoji Android SDK UI](https://github.com/imojiengineering/imoji-android-sdk-ui) project within the upcoming month. All our samples will have animated support for reference.
