### ISSUE TITLE
having duplicate app_name variable

### ISSUE THREAD

**Issue by jaygauten** [imojiengineering/imoji-android-sdk#12]
after declaring as a dependency - version 2.0.3 - to my project then rebuild, i got this error:

`Error:(3663, 33) error: variable app_name is already defined in class string`

heres my app details:
sdktargetversion: 23
minsdkversion: 16
buildtoolsversion: 23.0.2

thanks

**Comment by nkhoshini** [comment]
I've removed app_name from our manifest file. This should avoid clashes with your application. Let us know if it doesn't. The build should be live in Maven Central in a couple of hours.

**Comment by jaygauten** [comment]
@nkhoshini thanks..

**Comment by jaygauten** [comment]
@nkhoshini the bug still exists
