### ISSUE TITLE
Improve sticker's load

### ISSUE THREAD

**Issue by deepakbharanikana** [imojiengineering/imoji-android-sdk#13]
sticker's load taking lot of time even with hi-speed internet on first launch.. user's were not sure what's happening and leading to a bad first time experience

**Comment by nkhoshini** [comment]
Hi @deepakbharanikana can you pinpoint where the slowness comes from? Is is the image downloads, server calls, etc? Are you loading webp versions of the images? They substantially smaller than PNG's to download. There are many imaging libraries around with webp support. We offer [bifrost](https://github.com/imojiengineering/bifrost) but you can also use [Fresco](https://github.com/facebook/fresco) or other libraries for that.

**Comment by nkhoshini** [comment]
Closing… Please recreate the issue if you are still experiencing problems

**Comment by deepakbharanikana** [comment]
We are using the messaging sample code from your repo in our app. When the app is launched for first time and tapped on a button that shows stickers,  here nothing will load..  If I close the app from background and start again then everything works normal

Thanks Deepak

Sent from Yahoo Mail on Android 
 
  On Tue, May 3, 2016 at 3:02 PM, Nima Khoshini<notifications@github.com> wrote:   
Closing… Please recreate the issue if you are still experiencing problems

**Comment by nkhoshini** [comment]
Have you tried overriding onError in your WrappedAsyncTask to see if anything is showing up there?

Ex: https://github.com/imojiengineering/imoji-android-sdk/blob/master/imoji-android-sdk/src/androidTest/java/io/imoji/sdk/ErrorTests.java#L74

**Comment by deepakbharanikana** [comment]
Will let you know 

Sent from Yahoo Mail on Android 
 
  On Tue, May 3, 2016 at 5:20 PM, Nima Khoshini<notifications@github.com> wrote:   
Have you tried overriding onError in your WrappedAsyncTask to see if anything is showing up there?

Ex: https://github.com/imojiengineering/imoji-android-sdk/blob/master/imoji-android-sdk/src/androidTest/java/io/imoji/sdk/ErrorTests.java#L74
