### ISSUE TITLE
WrappedAsyncTask can't be executed on Andoid 4.0 and 4.1 devices

### ISSUE THREAD

**Issue by shewenbiao** [imojiengineering/imoji-android-sdk#14]
I have run the imoji sdk sample(https://github.com/imojiengineering/imoji-android-sdk/tree/master/samples/sdksample) on Andorid 4.1 and 4.0 devices, but it always in a loading state after I click the button to load Trending imojis. I found the problem in the following code:
```ruby
public static abstract class WrappedAsyncTask<V> extends AsyncTask<Future<V>, Void, V> {
        @SafeVarargs
        @Override
        protected final V doInBackground(Future<V>... params) {
            try {
                FutureTask<V> task = (FutureTask<V>) params[0];
                THREAD_POOL_EXECUTOR_SERVICE.submit(task);
                return task.get();
            } catch (InterruptedException | ExecutionException e) {
                Log.e(ApiTask.class.getName(), "Unable to perform async task", e);
                Message message = MAIN_LOOP_HANDLER.obtainMessage(
                        WRAPPED_ASYNC_ERROR_MESSAGE,
                        new Pair<WrappedAsyncTask<?>, Throwable>(this, e)
                );
                MAIN_LOOP_HANDLER.dispatchMessage(message);

                throw new RuntimeException("Unable to perform async task", e);
            }
        }

        @Override
        protected abstract void onPostExecute(V v);

        /**
         * Called when the ApiTask encounters an error.
         *
         * @param error The error that occurred making the API call.
         */
        @SuppressWarnings("UnusedParameters")
        protected void onError(@NonNull Throwable error) {

        }
    }
```
The `doInBackground()` method can't be excuted on android 4.0 and 4.1 devices.

**Comment by nkhoshini** [comment]
The problem looked to be specific to single processor phones. Our ExecutorService was running out of threads when grabbing OAuth tokens. Bumping the minimum count up by one solves the issue while testing with the simulators. Let us know how it works for you. The build (2.1.1) has been released to Maven and will be live in a couple of hours.

**Comment by shewenbiao** [comment]
@nkhoshini 
Thank you for you reply, I will tell you the result as soon as possible.

**Comment by shewenbiao** [comment]
@nkhoshini 
The problem has fixed. Thank you!

**Comment by nkhoshini** [comment]
Excellent! Glad to hear it worked 😃
