### ISSUE TITLE
Runtime exception when no internet available

### ISSUE THREAD

**Issue by rimeissner** [imojiengineering/imoji-android-sdk#15]
When I turn on airplane mode the AsyncTask is throwing a RuntimeException ("Unable to perform async task" -> "Unable to resolve host ...") that is cashing the whole application. Is there any way to prevent this? We are using version 2.1.2 of the SDK. This was tested on a Nexus 5 with Android 6.0

This seems to be happening because the AsyncTask is reraising all exceptions:

```
public static abstract class WrappedAsyncTask<V> extends AsyncTask<Future<V>, Void, V> {
    @SafeVarargs
    @Override
    protected final V doInBackground(Future<V>... params) {
        try {
            FutureTask<V> task = (FutureTask<V>) params[0];
            THREAD_POOL_EXECUTOR_SERVICE.submit(task);
            return task.get();
        } catch (ExecutionException e) {
            Log.e(ApiTask.class.getName(), "Unable to perform async task", e);
            Message message = MAIN_LOOP_HANDLER.obtainMessage(
                    WRAPPED_ASYNC_ERROR_MESSAGE,
                    new Pair<WrappedAsyncTask<?>, Throwable>(this, e)
            );
            MAIN_LOOP_HANDLER.dispatchMessage(message);
            throw new RuntimeException("Unable to perform async task", e);
        } catch (InterruptedException e) { // interrupts will naturally occur from cancelling
            throw new RuntimeException("WrappedAsyncTask interrupted", e);
        }
    }
}
```

**Comment by nkhoshini** [comment]
Thanks for reporting this! I'll try to reproduce it on our side… I've seen some implementations of async tasks handle errors by returning null for doInBackground and setting an error member field to the exception. That maybe the only feasible solution here but it'll require developers to perform null checks.

**Comment by nkhoshini** [comment]
Have a fix in place in b1e2551dfb7133af634944a29b546444b4656b74
We'll cancel the tasks whenever ExectutionException's are caught. This ensures that callers don't need to perform nasty null checks in onPostExecute to check for errors and can instead override onError.

**Comment by nkhoshini** [comment]
Pushed over version 2.1.3, please let us know if it's not working for you guys

**Comment by rimeissner** [comment]
Thanks for the fast update, will check it out soon :)
