### ISSUE TITLE
Retrieving categories does not work on first run after installation

### ISSUE THREAD

**Issue by UrK** [imojiengineering/imoji-android-sdk#17]
Hi.
We have a lot of complaints from users about images not loading. After some investigation, we discovered that imoji categories loader never calls any callback on first run after installation.

Here is part of our code:
Log shows no messages after execution.

```
ImojiSDK.getInstance()
        .createSession(context)
        .getImojiCategories(fetchConfig)
        .executeAsyncTask(new ApiTask.WrappedAsyncTask<CategoriesResponse>() {
            @Override
            protected void onCancelled(CategoriesResponse categoriesResponse) {
                Log.v(TAG, "Categories retrieval cancelled");
            }

            @Override
            protected void onPostExecute(CategoriesResponse categoriesResponse) {
                Log.v(TAG, "Retrieved " + (result != null ? result.size() : -1) + " categories);
            }

            @Override
            protected void onError(@NonNull Throwable error) {
                Log.v(TAG, "Failed to retrieve categories for classiciation " + classificationName);
            }
        });
```

**Comment by nkhoshini** [comment]
Is getImojiCategories the only method experiencing this behavior @UrK ?

**Comment by UrK** [comment]
This is the first call we are using in the app. So, it blocks rest of the calls.

**Comment by UrK** [comment]
And I forgot to mention that Imoji is called from background thread:

    new Thread(new Runnable() {
        ImojiSDK.getInstance()
            .createSession(context)
            .getImojiCategories(fetchConfig)
            .executeAsyncTask(...)
    });

**Comment by nkhoshini** [comment]
Do you get the same result if you call [executeAsyncTaskOnExecutor](http://static.javadoc.io/io.imoji.sdk/imoji-sdk/2.1.7/io/imoji/sdk/ApiTask.html#executeAsyncTaskOnExecutor(io.imoji.sdk.ApiTask.WrappedAsyncTask, java.util.concurrent.ExecutorService)

```java
ThreadPoolExecutor threadPoolExecutor = new ThreadPoolExecutor(10, 10, 10, TimeUnit.SECONDS, new LinkedBlockingDeque<Runnable>());

        sdkSession.getImojiCategories(new CategoryFetchOptions(Category.Classification.None))
                .executeAsyncTaskOnExecutor(new ApiTask.WrappedAsyncTask<CategoriesResponse>() {
                    @Override
                    protected void onPostExecute(CategoriesResponse categoriesResponse) {

                    }
                }, threadPoolExecutor);
``

**Comment by nkhoshini** [comment]
I'm wondering if its similar to #14 where the thread pool limit is exhausted.

**Comment by UrK** [comment]
@nkhoshini, sorry. Google was sending GitHub's emails into Spam folder. For now I solved the issue by working via synchronous methods. Will try your suggestion and let you know. Were you able to reproduce it on your side?

**Comment by UrK** [comment]
Regarding https://github.com/imojiengineering/imoji-android-sdk/issues/14, this happens on Lollipop devices too.

**Comment by nkhoshini** [comment]
@UrK I haven't been able to reproduce this on my end. I'm guessing a slow network connection followed by numerous requests causes the thread pool to get backed up.
