### ISSUE TITLE
App always rejected by Google because of Imoji

### ISSUE THREAD

**Issue by fraxool** [imojiengineering/imoji-android-sdk#18]
Hello,

I integrated this awesome library into my app and after submitting it to the Google Play Store, it has been rejected (twice).

Here is the message from Google : 

> Remove any content owned by a third party from your app. Your app store listing contains images of Pokemon characters, MLB logos, Olympic logo and more in app experience.

Is there a way to select only a few categories to be displayed so I don't use copyrighted stickers?

Thanks,
Axel

**Comment by nkhoshini** [comment]
Hi @fraxool, there's not a method at the moment to pick and choose categories. However you can attempt to load either Generic or Artist category classification types instead of Trending.

```java
sdkSession.getImojiCategories(new CategoryFetchOptions(Category.Classification.Artist)).executeAsyncTask(new ApiTask.WrappedAsyncTask<CategoriesResponse>() {
            @Override
            protected void onPostExecute(CategoriesResponse categoriesResponse) {
            }
}
```
