### ISSUE TITLE
imoji implementation not synincg with gradle due to recylerview

### ISSUE THREAD

**Issue by nibha181** [imojiengineering/imoji-android-sdk#19]
I was trying to implement sticker in my app from this link

https://developer.imoji.io/#/home#platform-android

as soon as,I add dependency, I am getting this error:

Warning:Module 'com.android.support:recyclerview-v7:24.1.1' depends on one or more Android Libraries but is a jar
Error:A problem occurred configuring project ':app'.
> Could not find recyclerview-v7.jar (com.android.support:recyclerview-v7:24.1.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/recyclerview-v7/24.1.1/recyclerview-v7-24.1.1.jar
gradle:

dependencies {
    compile 'testfairy:testfairy-android-sdk:1.3.4@aar'
    compile fileTree(include: ['*.jar'], dir: 'libs')
    //google play services lib
    //    compile 'com.google.android.gms:play-services:9.2.1'
    // Recommended for location services

    compile 'me.grantland:autofittextview:0.2.1'
    compile 'com.google.android.gms:play-services-location:9.2.0'
    compile 'com.google.android.gms:play-services-plus:9.2.0'
    compile 'com.google.android.gms:play-services-analytics:9.2.0'
    compile 'com.google.android.gms:play-services-auth:9.2.0'

    compile 'com.google.firebase:firebase-analytics:9.2.0'
    compile 'com.google.firebase:firebase-messaging:9.2.0'
    compile 'com.google.firebase:firebase-ads:9.2.0'
    compile 'com.google.firebase:firebase-auth:9.2.0'
    compile 'com.google.firebase:firebase-crash:9.2.0'
    compile 'com.google.firebase:firebase-invites:9.2.0'

    compile 'com.google.code.gson:gson:2.4'

    compile 'com.clevertap.android:clevertap-android-sdk:3.1.0'

    compile 'com.android.support:support-v4:24.1.1'
    compile 'com.android.support:design:24.1.1'
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.android.support:cardview-v7:24.1.1'
    compile 'com.android.support:recyclerview-v7:24.1.1'
    compile 'com.android.support:multidex:1.0.0'

    compile 'com.readystatesoftware.sqliteasset:sqliteassethelper:2.0.1'

    compile 'com.facebook.android:facebook-android-sdk:4.14.1'

    compile 'cn.pedant.sweetalert:library:1.3'
    compile 'com.android.volley:volley:1.0.0'
    compile 'com.github.bumptech.glide:volley-integration:1.4.0@aar'

    compile 'com.sun.mail:android-mail:1.5.5'
    compile 'com.sun.mail:android-activation:1.5.5'
    compile 'com.etsy.android.grid:library:1.0.5'
    compile 'com.github.paolorotolo:appintro:4.0.0'
    compile('com.twitter.sdk.android:twitter:1.14.1@aar') {
        transitive = true;
    }
    compile ('io.imoji.sdk:imoji-sdk-ui:+@aar') {
        transitive=true
    }
    apply plugin: 'com.google.gms.google-services'
    apply plugin: 'io.fabric'
Anyone has idea, why this error comes?

**Comment by nkhoshini** [comment]
Let's track this in the issue you have for the SDK-UI project:

https://github.com/imojiengineering/imoji-android-sdk-ui/issues/10
