### ISSUE TITLE
Imoji Creation Tool should wait until upload completes prior to returning

### ISSUE THREAD

**Issue by nkhoshini** [imojiengineering/imoji-android-sdk#6]
Update the creation tool to dismiss itself only once it has completed uploading the image to the server. Currently it dismisses immediately…

**Comment by stabib** [comment]
There are two modes. One that waits until upload is completed, and another where it returns immediately. This is user driven through the Activity flag ImojiEditorActivity.RETURN_IMMEDIATELY_BUNDLE_ARG_KEY. Take a look at https://github.com/imojiengineering/imoji-android-sdk-ui/blob/master/README.md, specifically the  ImojiCreater section item 5. Let me know if this makes sense.

**Comment by Alamgir** [comment]
@stabib so the first mode will put up a spinner and only dismiss the creation flow once the URLs are set and final?

**Comment by stabib** [comment]
@Alamgir Exactly, and that is the default. To return immediately, which doesn't return an Imoji object, you have to explicitly pass in the activity flag.

**Comment by Alamgir** [comment]
@stabib Guys so after testing in 0.1.7, the Imoji object extra returned in the resulting intent does not have the URLs set

**Comment by stabib** [comment]
@nkhoshini, are the on-demand generated URLs being sent down?

**Comment by nkhoshini** [comment]
Turns out the URL's were not being sent over for the fetch imojis by id call. This has been addressed on the server. Works now :+1:
