### ISSUE TITLE
Bad Request, No Living Connections.

### ISSUE THREAD

**Issue by liamcottle** [imojiengineering/imoji-android-sdk#8]
Hi guys,

I've had Imoji integrated into one of my apps for quite some time now. Everything has been running smoothly.

However, just recently (today from what I've noticed), the Imoji API is returning a bad response to all API calls from the Android SDK other than the initial `/oauth/token` request (which still works fine).

This is the server response I am receiving, for a request to:
`/v2/imoji/categories/fetch?access_token=redacted`
```
400 Bad Request
```
```
{
	"message": "No Living connections"
}
```

Any help would be appreciated :)

Cheers,
Liam Cottle

**Comment by liamcottle** [comment]
This appears to have resolved itself. However, any information on what happened ?

**Comment by nkhoshini** [comment]
Hi Liam, we had downtime with our search engine for about an hour on Monday, I apologize for that. We're working on getting a formal status page on our main site together so developers can get insight into whats going on.

Thanks!

**Comment by liamcottle** [comment]
Cheers guys, great stuff!
