### ISSUE TITLE
SDK update plans?

### ISSUE THREAD

**Issue by SteveYurka** [imojiengineering/imoji-android-sdk#9]
Thanks for the SDK first off, our iOS user's are loving the stickers

We have almost released our Android version of our application, and I've noticed that some the features we use in the iOS SDK are not available yet for Android

Do you have any plans currently to implement different rendering options (eg, bordered VS no border, animated stickers)?

I am wondering if I should go ahead and do this myself, or wait a little bit for the next release, as the current version is from Dec 2015

Also I have noticed you guys have recently removed all stickers which are possibly inappropriate (but we're extremely fun!), as our user's have been asking us if we have been removing them. Are there any plans to allow for a R18+ mode, or is this just imoji's stance on content

Thanks!

**Comment by nkhoshini** [comment]
Hi Steve, thanks for reaching out! We're looking to update the Android SDK to match the functionality of the iOS one soon. The next version of the Android SDK will be revamped to work a lot like the iOS one for consistency. The current timeline is about 2-4 weeks for us.

In terms of getting more content, we can definitely whitelist your developer account to get all search results. Send me an email at nima@imojiapp.com with your client id and I'll get that setup.

Cheers!
